# Generated by Django 4.2.3 on 2024-01-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0004_department_studentid_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='departmet',
            new_name='department',
        ),
    ]
